name: Publish package
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Config poetry
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Publish package
      run: poetry publish --build -n
