name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --without dev -E all

    - name: pytest
      run: poetry run pytest --cov --cov-fail-under=95 --junitxml=test-results/all.xml

    - name: ruff
      run: poetry run ruff .

    - name: mypy
      run: poetry run mypy .

    - name: bandit
      run: poetry run bandit . -r -c bandit.yaml
